language: java
jdk: openjdk8
services:
- xvfb
- docker
dist: xenial
addons:
  sonarcloud:
    organization: continuous-integration-and-deployment
    token:
      secure: "XeWtaoUBTwNMie4GDBDDfCEfiSacpD0wnvUjYy0CbeEnTD2yEZyTESvnIA4Ve76E9q+g4kqNtJyShleksbDMMnMY7wFQ2dn0pvY1TPkROLnA+Lp8T/L43N0bcHWXnjpFLh9D0xJGToj1JnL9IegSfmMPJKiTC2JMwVhUyEi4eAAwvFsfP8GXXJ9op2XMg34VPL1oWEzBH1m0SdBiyPefgoYw8cxSSiOOazZJy+QaUIzI/WHo957MWAZWaUVCzAlARAlE3H6t8bVEb55AWkOwzTLokckcSmcB3lJOd9oTwM6PN/Vl4EYnJo10IHuOfrZS0/OilcUCle5OV+/xu2KJrswL7tmeGUbFhO40EjiITiHLXX9Vw5i7pt0e5a3gqMyatyxIC05Oj+nS+k/j/PvMqCZ97iO0SckOUQEXV58lcbNcycOWOnXaUsKpDA0r0kFG5pxmrJZo+puNHxBQFXomPyHzHNyQpzNHkc+hSUc2Shap6oThVuTjqP0FNoeNaDbU0a5FIQ4Am2kJm99MbrNy3h3xbC0q9nmKbtwbGxegL6kgmf7AD2HH8RdG7S3QuW10qGb8X6erXcXjQsd8AnvZ3275xtjnc5Nxc3iOGXB5c4HAs7UTHVyxIFjf5E0wFeCztnDfZyAVtt+dO6Y6boBzY8qwxzDyzNO5CJwSFUTQgyU="
before_install:
- sudo apt update
- sudo apt install openjfx
- echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_USERNAME" --password-stdin
- docker pull openjdk:8-jdk
install: true
script:
- "./build.sh"
after_success:
- bash <(curl -s https://codecov.io/bash) -t "$CODECOV_TOKEN"